In [1]:
import numpy as np
arr = np.arange(0,10)

In [2]:
arr[8]
arr[1:5]
#Setting a value with index range (Broadcasting)
arr[0:5]=100

#Show
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [3]:
#Important notes on Slices
slice_of_arr = arr[0:6]

#Show slice
slice_of_arr

#Change Slice
slice_of_arr[:]=99

#Show Slice again
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [4]:
#To get a copy, need to be explicit
arr_copy = arr.copy()

arr_copy

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [5]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45]))

#Show
arr_2d
# Format is arr_2d[row][col] or arr_2d[row,col]

# Getting individual element value
arr_2d[1]
arr_2d[1][0]
#Shape bottom row
arr_2d[:2,1:]
arr_2d[2,:]

array([35, 40, 45])

In [6]:
arr2d = np.zeros((10,10))
arr_length = arr2d.shape[1]

In [7]:
#Set up array

for i in range(arr_length):
    arr2d[i] = i
    
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [8]:
arr2d[[2,4,6,8]]
#Allows in any order
arr2d[[6,4,2,7]]

array([[6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.]])

In [9]:
arr > 4
bool_arr = arr>4
arr[bool_arr]
x = 2
arr[arr>x]

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [10]:
arr + arr

array([198, 198, 198, 198, 198, 198,  12,  14,  16,  18])

In [11]:
arr * arr

array([9801, 9801, 9801, 9801, 9801, 9801,   36,   49,   64,   81])

In [12]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Warning on division by zero, but not an error!
# Just replaced with nan
arr/arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [14]:
# Also warning, but not an error instead infinity
1/arr

array([0.01010101, 0.01010101, 0.01010101, 0.01010101, 0.01010101,
       0.01010101, 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [15]:
arr**3

array([970299, 970299, 970299, 970299, 970299, 970299,    216,    343,
          512,    729], dtype=int32)

## Universal Array Functions

Numpy comes with many [universal array functions](http://docs.scipy.org/doc/numpy/reference/ufuncs.html), which are essentially just mathematical operations you can use to perform the operation across the array. Let's show some common ones:

In [16]:
#Taking Square Roots
np.sqrt(arr)

array([9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
       9.94987437, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [17]:
#Calcualting exponential (e^)
np.exp(arr)

array([9.88903032e+42, 9.88903032e+42, 9.88903032e+42, 9.88903032e+42,
       9.88903032e+42, 9.88903032e+42, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

In [18]:
np.max(arr) #same as arr.max()

99

In [19]:
np.sin(arr)

array([-0.99920683, -0.99920683, -0.99920683, -0.99920683, -0.99920683,
       -0.99920683, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [20]:
np.log(arr)

array([4.59511985, 4.59511985, 4.59511985, 4.59511985, 4.59511985,
       4.59511985, 1.79175947, 1.94591015, 2.07944154, 2.19722458])